# Site
name: 'The 2nd Trial'
author: 'Andrea Tino'
description: 'Learn Mathematics thorugh the problems and questions of the Italian National Exam.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'the-2nd-trial'
email: 'example@gmail.com'
# newsletter-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    andrea:
      name:           Andrea
      site:           https://github.com/andry-tino
      avatar:         assets/images/avatar_andrea.png
      bio:            "Hi, I am Andrea, the author and creator of The 2nd Trial. I write about a lot of different things, feel free to engage with me."
      email:          info@the2ndtrial.org
      twitter:        https://twitter.com/the2ndtrial

    anonymous:
      name:           Anonymous
      avatar:         assets/images/avatar_anonymous.png
      bio:            "Hi I am an anonymous author. I prefer keeping a veil of mistery around me, so deal with it."
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: andrea
      avatar: assets/images/avatar_andrea.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
kramdown:
  math_engine: katex
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]