title: The 2nd Trial
email: info@the2ndtrial.org
description: The 2nd Trial is coming soon
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/the-second-trial" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: __antino
github_username: andry-tino

# Build settings
markdown: kramdown
theme:
plugins:
  - jekyll-feed

include:
  - _pages
